[package]
name = "twitch_ircv3_parse"
version = "0.0.1"
edition = "2021"

[dependencies]
ircv3_parse = "0.0.8"
nom = "7.1.3"
serde = { version = "1.0.197", features = ["derive"] }
twitch_api = { path = "../twitch_api" }

[dev-dependencies]
pretty_assertions = "1.4.0"
serde_json = "1.0.114"
